default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: NovaSenha123!
  host: localhost

development:
  <<: *default
  database: task_manager_app_development

test:
  <<: *default
  database: task_manager_app_test

production:
  <<: *default
  database: task_manager_app_production
  username: task_manager_app
  password: <%= ENV["TASK_MANAGER_APP_DATABASE_PASSWORD"] %>
